### ISSUE TITLE
about idbp-cnn denoising

### ISSUE THREAD

**Issue by williamschandra** [tomtirer/IDBP#1]
hi, can you let me know the kernels for denoising in idbp-cnn? im trying to use identity matrix but my result is wrong, also can u let me know whats and how to calculate the xk formulas? thankyou.., im stuck on that

**Comment by tomtirer** [comment]
Hi,
Note that the goal of the IDBP framework is to solve linear inverse problems **other than denoising** using off-the-shelf denoising algorithms. 
In the denoising case (i.e. when H=I_n) the framework coincides with the plain denoising. 
So, if you want to perform denoising, you don't need this iterative algorithm... just apply a denoiser on y.
IDBP-CNN denotes the IDBP method when we plugged in it the pre-trained denoisers from IRCNN (https://github.com/cszn/IRCNN) (and solved with them inpainting, deblurring, super-resolution,...).

**Comment by williamschandra** [comment]
Thank you for replying
So when we want to use IDBP for solving denoising, inpainting and deblurring what "H" do we use and we set it 1 by 1 or the program auto tuning the "H"

**Comment by tomtirer** [comment]
See the first paragraph in the second page of the paper https://arxiv.org/pdf/1710.06647.pdf.
In many cases there are fast ways to implement the operator H (faster than matrix multiplication). For example, in inpainting just keep the pixels in certain places, and in debluring apply convolution with a blur kernel h. The algorithm requires knowledge on the measurement operator (e.g. the indices of the missing pixels in inpainting and the blur kernel h in deblurring).
